
### Attempt to create a game without data (ERROR)
POST http://localhost:3001/api/games
Content-Type: application/json

{
}

### Attempt to create a game without title nor picture (ERROR)
POST http://localhost:3001/api/games
Content-Type: application/json

{
  "played": "Played",
  "release_year": 2000,
  "categories": "Adventure"
}

### Attempt to create a game with only title and picture (SUCCESS)
POST http://localhost:3001/api/games
Content-Type: application/json

{
  "title": "Example game",
  "img": "https://image.api.playstation.com/cdn/EP0002/CUSA07399_00/bPXMfRCtjGgvIS0BxOWqVsn94MAMLMkE.png"
}

### Attempt to create a game with only title (ERROR)
POST http://localhost:3001/api/games
Content-Type: application/json

{
  "title": "Example game"
}

### Attempt to create a game with only picture (ERROR)
POST http://localhost:3001/api/games
Content-Type: application/json

{
  "img": "https://image.api.playstation.com/cdn/EP0002/CUSA07399_00/bPXMfRCtjGgvIS0BxOWqVsn94MAMLMkE.png"
}

### Attempt to create a game with all the possible data (SUCCESS)
POST http://localhost:3001/api/games
Content-Type: application/json

{
  "title": "Example",
  "img": "https://image.api.playstation.com/cdn/EP0002/CUSA07399_00/bPXMfRCtjGgvIS0BxOWqVsn94MAMLMkE.png",
  "played": "Played",
  "release_year": 2017,
  "categories": "Platformer, Action, Adventure"
}
